### ISSUE TITLE
Consider splitting `probe_selector` into separate items for VID/PID and serial number

### ISSUE THREAD

**Issue by hannobraun** [probe-rs/cargo-embed#14]
**Is your feature request related to a problem? Please describe.**

I have a setup with two identical development boards, so I'm adding the serial number to `probe_selector` to distinguish them. This works fine.

My project will be used by other people too, who will have the same boards but different serial numbers. `Embed.local.toml` seems like the place to define the serial number, but I can't do so without repeating the USB VID/PID there.

**Describe the solution you'd like**

I'd like the configuration to look something like this:

``` toml
[probe]
usb = "1fc9:0132" # or call `vid_pid`, or `usb_vid_pid`; I like `usb` because it's concise
serial = "0F01D03A"
```

Then I can easily define the VID/PID in `Embed.toml` and tell users to specify the serial number in `Embed.local.toml`.

**Describe alternatives you've considered**

Maybe the syntax of `probe_selector` could be made more flexible. Something like `::0F01D03A` to override the serial number, but leave VID/PID as-is. This seems unnecessarily complex though. Splitting the selector into two items is a cleaner solution.
