### ISSUE TITLE
Fix UX paper-cut - invalid fields (e.g. typos) in configuration files are silently ignored

### ISSUE THREAD

**Issue by tim-seoss** [probe-rs/cargo-embed#167]
It's currently possible to add fields to the configuration sources which are ignored (e.g. because they're completely invalid, or typos).  e.g.

```toml
[default.gdb]
# This typo (should be "enabled", NOT "enable") should be flagged, but it's silently ignored
enable = true
```

I've dug about in the config code, and it looks non-trivial to add this feature because of the way nesting has been implemented atop `config`.  One possible solution would be to switch from using the `config` crate (which seems to be defacto deprecated by its maintainer) to `figment` - https://crates.io/crates/figment - which can be made to trivially detect this, and report the source (e.g. file path, and line number) of the spurious entry.
